/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_MJPC_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {0, 3, 5, 8, 9};
static const casadi_int casadi_s2[5] = {1, 4, 6, 7, 10};
static const casadi_int casadi_s3[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static const casadi_int casadi_s4[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s7[19] = {33, 5, 0, 3, 5, 7, 9, 11, 1, 20, 21, 13, 16, 1, 2, 2, 4, 4, 5};
static const casadi_int casadi_s8[3] = {5, 0, 0};

/* motor_reference:(i0[3])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5;
  /* #0: @0 = 0.0213523 */
  w0 = 2.1352344730507629e-02;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = 52.4282 */
  w3 = 5.2428199999999997e+01;
  /* #4: @2 = (@2/@3) */
  w2 /= w3;
  /* #5: @3 = 0.10007 */
  w3 = 1.0007019123296242e-01;
  /* #6: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #7: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #8: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #9: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #10: @4 = (@4+@5) */
  w4 += w5;
  /* #11: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #12: @3 = (@3*@4) */
  w3 *= w4;
  /* #13: @2 = (@2+@3) */
  w2 += w3;
  /* #14: @0 = (@0+@2) */
  w0 += w2;
  /* #15: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* inv_left:(i0)->(o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = tan(@1) */
  w2 = tan( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #5: @3 = -0.16113 */
  w3 = -1.6113000000000000e-01;
  /* #6: @1 = tan(@1) */
  w1 = tan( w1 );
  /* #7: @3 = (@3*@1) */
  w3 *= w1;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @0 = (@0/@2) */
  w0 /= w2;
  /* #10: @0 = atan(@0) */
  w0 = atan( w0 );
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* inv_right:(i0)->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = tan(@1) */
  w2 = tan( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #5: @3 = 0.16113 */
  w3 = 1.6113000000000000e-01;
  /* #6: @1 = tan(@1) */
  w1 = tan( w1 );
  /* #7: @3 = (@3*@1) */
  w3 *= w1;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @0 = (@0/@2) */
  w0 /= w2;
  /* #10: @0 = atan(@0) */
  w0 = atan( w0 );
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd3_motor_reference:(i0[3],out_o0[1x1,0nz],fwd_i0[3x3])->(fwd_o0[1x3]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, w5, w6, w7, w8, w9, w10;
  /* #0: @0 = 0.0190737 */
  w0 = 1.9073704609351459e-02;
  /* #1: @1 = input[2][0] */
  casadi_copy(arg[2], 3, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: @3 = 0.10007 */
  w3 = 1.0007019123296242e-01;
  /* #5: @4 = input[0][0] */
  casadi_copy(arg[0], 3, w4);
  /* #6: @5 = @4[1] */
  for (rr=(&w5), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #7: @6 = (2.*@5) */
  w6 = (2.* w5 );
  /* #8: @7 = @1[1] */
  for (rr=(&w7), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #9: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #10: @8 = @4[2] */
  for (rr=(&w8), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #11: @9 = (2.*@8) */
  w9 = (2.* w8 );
  /* #12: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #13: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #14: @7 = (@7+@10) */
  w7 += w10;
  /* #15: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #16: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #17: @5 = (@5+@8) */
  w5 += w8;
  /* #18: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #19: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #20: @7 = (@7/@5) */
  w7 /= w5;
  /* #21: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #22: @2 = (@2+@7) */
  w2 += w7;
  /* #23: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #24: @1 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+3 : 0, 3, w1);
  /* #25: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #26: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #27: @7 = @1[1] */
  for (rr=(&w7), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #28: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #29: @8 = @1[2] */
  for (rr=(&w8), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #30: @8 = (@9*@8) */
  w8  = (w9*w8);
  /* #31: @7 = (@7+@8) */
  w7 += w8;
  /* #32: @7 = (@7/@5) */
  w7 /= w5;
  /* #33: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #34: @2 = (@2+@7) */
  w2 += w7;
  /* #35: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #36: @1 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+6 : 0, 3, w1);
  /* #37: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #38: @0 = (@0*@2) */
  w0 *= w2;
  /* #39: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #40: @6 = (@6*@2) */
  w6 *= w2;
  /* #41: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #42: @9 = (@9*@2) */
  w9 *= w2;
  /* #43: @6 = (@6+@9) */
  w6 += w9;
  /* #44: @6 = (@6/@5) */
  w6 /= w5;
  /* #45: @3 = (@3*@6) */
  w3 *= w6;
  /* #46: @0 = (@0+@3) */
  w0 += w3;
  /* #47: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

/* fwd1_inv_right:(i0,out_o0[1x1,0nz],fwd_i0)->(fwd_o0) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #5: @3 = (@1/@3) */
  w3  = (w1/w3);
  /* #6: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #7: @4 = 0.24477 */
  w4 = 2.4476999999999999e-01;
  /* #8: @5 = 0.16113 */
  w5 = 1.6113000000000000e-01;
  /* #9: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #10: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #11: @4 = (@4+@6) */
  w4 += w6;
  /* #12: @3 = (@3/@4) */
  w3 /= w4;
  /* #13: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #14: @0 = (@0*@6) */
  w0 *= w6;
  /* #15: @0 = (@0/@4) */
  w0 /= w4;
  /* #16: @4 = (@0/@4) */
  w4  = (w0/w4);
  /* #17: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #18: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #19: @1 = (@1/@2) */
  w1 /= w2;
  /* #20: @5 = (@5*@1) */
  w5 *= w1;
  /* #21: @4 = (@4*@5) */
  w4 *= w5;
  /* #22: @3 = (@3-@4) */
  w3 -= w4;
  /* #23: @4 = 1 */
  w4 = 1.;
  /* #24: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #25: @4 = (@4+@0) */
  w4 += w0;
  /* #26: @3 = (@3/@4) */
  w3 /= w4;
  /* #27: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd1_inv_left:(i0,out_o0[1x1,0nz],fwd_i0)->(fwd_o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #5: @3 = (@1/@3) */
  w3  = (w1/w3);
  /* #6: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #7: @4 = 0.24477 */
  w4 = 2.4476999999999999e-01;
  /* #8: @5 = -0.16113 */
  w5 = -1.6113000000000000e-01;
  /* #9: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #10: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #11: @4 = (@4+@6) */
  w4 += w6;
  /* #12: @3 = (@3/@4) */
  w3 /= w4;
  /* #13: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #14: @0 = (@0*@6) */
  w0 *= w6;
  /* #15: @0 = (@0/@4) */
  w0 /= w4;
  /* #16: @4 = (@0/@4) */
  w4  = (w0/w4);
  /* #17: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #18: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #19: @1 = (@1/@2) */
  w1 /= w2;
  /* #20: @5 = (@5*@1) */
  w5 *= w1;
  /* #21: @4 = (@4*@5) */
  w4 *= w5;
  /* #22: @3 = (@3-@4) */
  w3 -= w4;
  /* #23: @4 = 1 */
  w4 = 1.;
  /* #24: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #25: @4 = (@4+@0) */
  w4 += w0;
  /* #26: @3 = (@3/@4) */
  w3 /= w4;
  /* #27: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* f1tenth_MJPC_constr_h_fun_jac_uxt_zt:(i0[26],i1[7],i2[],i3[])->(o0[5],o1[33x5,11nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4;
  casadi_real *w0=w+15, w1, *w2=w+23, w3, w4, *w5=w+51, w6, w7, *w8=w+56, *w10=w+67, *w11=w+95, *w12=w+100, *w13=w+123, *w14=w+127, *w15=w+129, w16, w17, *w18=w+133, *w19=w+136, w20;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 7, w0);
  /* #1: @1 = @0[1] */
  for (rr=(&w1), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 26, w2);
  /* #3: @3 = @2[13] */
  for (rr=(&w3), ss=w2+13; ss!=w2+14; ss+=1) *rr++ = *ss;
  /* #4: @4 = @2[14] */
  for (rr=(&w4), ss=w2+14; ss!=w2+15; ss+=1) *rr++ = *ss;
  /* #5: @5 = horzcat(@1, @3, @4) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #6: @5 = @5' */
  /* #7: @3 = motor_reference(@5) */
  arg1[0]=w5;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #9: @3 = @2[9] */
  for (rr=(&w3), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #10: @4 = inv_left(@3) */
  arg1[0]=(&w3);
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @6 = @2[6] */
  for (rr=(&w6), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #12: @7 = inv_right(@6) */
  arg1[0]=(&w6);
  res1[0]=(&w7);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @4 = (@4-@7) */
  w4 -= w7;
  /* #14: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #15: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #16: @1 = (@1-@4) */
  w1 -= w4;
  /* #17: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #18: @1 = @0[4] */
  for (rr=(&w1), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #19: @4 = (@4-@1) */
  w4 -= w1;
  /* #20: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #21: @4 = @0[5] */
  for (rr=(&w4), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #22: @1 = (@1-@4) */
  w1 -= w4;
  /* #23: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #24: @8 = zeros(33x5,11nz) */
  casadi_clear(w8, 11);
  /* #25: @9 = 00 */
  /* #26: @10 = ones(33x1,28nz) */
  casadi_fill(w10, 28, 1.);
  /* #27: {@11, @12} = vertsplit(@10) */
  casadi_copy(w10, 5, w11);
  casadi_copy(w10+5, 23, w12);
  /* #28: @1 = @11[1] */
  for (rr=(&w1), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #29: @4 = horzcat(@1, @9, @9) */
  rr=(&w4);
  *rr++ = w1;
  /* #30: @4 = @4' */
  /* #31: @13 = ones(33x1,4nz) */
  casadi_fill(w13, 4, 1.);
  /* #32: {@14, @15} = vertsplit(@13) */
  casadi_copy(w13, 2, w14);
  casadi_copy(w13+2, 2, w15);
  /* #33: @7 = @15[1] */
  for (rr=(&w7), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #34: @16 = horzcat(@9, @7, @9) */
  rr=(&w16);
  *rr++ = w7;
  /* #35: @16 = @16' */
  /* #36: @7 = ones(33x1,1nz) */
  w7 = 1.;
  /* #37: {NULL, @17} = vertsplit(@7) */
  w17 = w7;
  /* #38: @7 = @17[0] */
  for (rr=(&w7), ss=(&w17)+0; ss!=(&w17)+1; ss+=1) *rr++ = *ss;
  /* #39: @17 = horzcat(@9, @9, @7) */
  rr=(&w17);
  *rr++ = w7;
  /* #40: @17 = @17' */
  /* #41: @18 = horzcat(@4, @16, @17) */
  rr=w18;
  *rr++ = w4;
  *rr++ = w16;
  *rr++ = w17;
  /* #42: @19 = dense(@18) */
  casadi_densify(w18, casadi_s0, w19, 0);
  /* #43: @18 = fwd3_motor_reference(@5, @9, @19) */
  arg1[0]=w5;
  arg1[1]=0;
  arg1[2]=w19;
  res1[0]=w18;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #44: {@4, @16, @17} = horzsplit(@18) */
  w4 = w18[0];
  w16 = w18[1];
  w17 = w18[2];
  /* #45: @7 = @12[6] */
  for (rr=(&w7), ss=w12+6; ss!=w12+7; ss+=1) *rr++ = *ss;
  /* #46: @20 = fwd1_inv_right(@6, @9, @7) */
  arg1[0]=(&w6);
  arg1[1]=0;
  arg1[2]=(&w7);
  res1[0]=(&w20);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #47: @20 = (-@20) */
  w20 = (- w20 );
  /* #48: @6 = @11[3] */
  for (rr=(&w6), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #49: @7 = (-@6) */
  w7 = (- w6 );
  /* #50: @11 = vertcat(@4, @20, @1, @7, @6) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w20;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w6;
  /* #51: (@8[0, 3, 5, 8, 9] = @11) */
  for (cii=casadi_s1, rr=w8, ss=w11; cii!=casadi_s1+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #52: @4 = @15[0] */
  for (rr=(&w4), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #53: @20 = fwd1_inv_left(@3, @9, @4) */
  arg1[0]=(&w3);
  arg1[1]=0;
  arg1[2]=(&w4);
  res1[0]=(&w20);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #54: @3 = @14[0] */
  for (rr=(&w3), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #55: @4 = (-@3) */
  w4 = (- w3 );
  /* #56: @1 = @14[1] */
  for (rr=(&w1), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #57: @1 = (-@1) */
  w1 = (- w1 );
  /* #58: @11 = vertcat(@16, @20, @4, @3, @1) */
  rr=w11;
  *rr++ = w16;
  *rr++ = w20;
  *rr++ = w4;
  *rr++ = w3;
  *rr++ = w1;
  /* #59: (@8[1, 4, 6, 7, 10] = @11) */
  for (cii=casadi_s2, rr=w8, ss=w11; cii!=casadi_s2+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #60: (@8[2] = @17) */
  for (rr=w8+2, ss=(&w17); rr!=w8+3; rr+=1) *rr = *ss++;
  /* #61: output[1][0] = @8 */
  casadi_copy(w8, 11, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_MJPC_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 146;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 146*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
