/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_MJPC_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static const casadi_int casadi_s1[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* motor_reference:(i0[3])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5;
  /* #0: @0 = 0.0213523 */
  w0 = 2.1352344730507629e-02;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = 52.4282 */
  w3 = 5.2428199999999997e+01;
  /* #4: @2 = (@2/@3) */
  w2 /= w3;
  /* #5: @3 = 0.10007 */
  w3 = 1.0007019123296242e-01;
  /* #6: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #7: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #8: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #9: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #10: @4 = (@4+@5) */
  w4 += w5;
  /* #11: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #12: @3 = (@3*@4) */
  w3 *= w4;
  /* #13: @2 = (@2+@3) */
  w2 += w3;
  /* #14: @0 = (@0+@2) */
  w0 += w2;
  /* #15: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* inv_left:(i0)->(o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = tan(@1) */
  w2 = tan( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #5: @3 = -0.16113 */
  w3 = -1.6113000000000000e-01;
  /* #6: @1 = tan(@1) */
  w1 = tan( w1 );
  /* #7: @3 = (@3*@1) */
  w3 *= w1;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @0 = (@0/@2) */
  w0 /= w2;
  /* #10: @0 = atan(@0) */
  w0 = atan( w0 );
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* inv_right:(i0)->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = tan(@1) */
  w2 = tan( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #5: @3 = 0.16113 */
  w3 = 1.6113000000000000e-01;
  /* #6: @1 = tan(@1) */
  w1 = tan( w1 );
  /* #7: @3 = (@3*@1) */
  w3 *= w1;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @0 = (@0/@2) */
  w0 /= w2;
  /* #10: @0 = atan(@0) */
  w0 = atan( w0 );
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* f1tenth_MJPC_constr_h_fun:(i0[26],i1[7],i2[],i3[])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+4;
  casadi_real *w0=w+8, w1, *w2=w+16, w3, w4, *w5=w+44, w6;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 7, w0);
  /* #1: @1 = @0[1] */
  for (rr=(&w1), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 26, w2);
  /* #3: @3 = @2[13] */
  for (rr=(&w3), ss=w2+13; ss!=w2+14; ss+=1) *rr++ = *ss;
  /* #4: @4 = @2[14] */
  for (rr=(&w4), ss=w2+14; ss!=w2+15; ss+=1) *rr++ = *ss;
  /* #5: @5 = horzcat(@1, @3, @4) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #6: @5 = @5' */
  /* #7: @3 = motor_reference(@5) */
  arg1[0]=w5;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #9: @3 = @2[9] */
  for (rr=(&w3), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #10: @4 = inv_left(@3) */
  arg1[0]=(&w3);
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @3 = @2[6] */
  for (rr=(&w3), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #12: @6 = inv_right(@3) */
  arg1[0]=(&w3);
  res1[0]=(&w6);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @4 = (@4-@6) */
  w4 -= w6;
  /* #14: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #15: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #16: @1 = (@1-@4) */
  w1 -= w4;
  /* #17: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #18: @1 = @0[4] */
  for (rr=(&w1), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #19: @4 = (@4-@1) */
  w4 -= w1;
  /* #20: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #21: @4 = @0[5] */
  for (rr=(&w4), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #22: @1 = (@1-@4) */
  w1 -= w4;
  /* #23: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_MJPC_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 48;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 48*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
