/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 4, 6, 9, 10};
static const casadi_int casadi_s2[6] = {0, 2, 5, 7, 8, 11};
static const casadi_int casadi_s3[8] = {3, 2, 0, 2, 3, 0, 1, 2};
static const casadi_int casadi_s4[4] = {0, 3, 20, 21};
static const casadi_int casadi_s5[4] = {0, 1, 2, 4};
static const casadi_int casadi_s6[42] = {33, 33, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 3, 20, 21, 20, 21};
static const casadi_int casadi_s7[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static const casadi_int casadi_s8[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s9[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[21] = {33, 6, 0, 1, 4, 6, 8, 10, 12, 20, 1, 20, 21, 0, 3, 1, 2, 2, 4, 4, 5};
static const casadi_int casadi_s12[3] = {6, 0, 0};

/* inv_right:(i0)->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = tan(@1) */
  w2 = tan( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #5: @3 = 0.16113 */
  w3 = 1.6113000000000000e-01;
  /* #6: @1 = tan(@1) */
  w1 = tan( w1 );
  /* #7: @3 = (@3*@1) */
  w3 *= w1;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @0 = (@0/@2) */
  w0 /= w2;
  /* #10: @0 = atan(@0) */
  w0 = atan( w0 );
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* motor_reference:(i0[3])->(o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5;
  /* #0: @0 = 0.0213523 */
  w0 = 2.1352344730507629e-02;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = 52.4282 */
  w3 = 5.2428199999999997e+01;
  /* #4: @2 = (@2/@3) */
  w2 /= w3;
  /* #5: @3 = 0.10007 */
  w3 = 1.0007019123296242e-01;
  /* #6: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #7: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #8: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #9: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #10: @4 = (@4+@5) */
  w4 += w5;
  /* #11: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #12: @3 = (@3*@4) */
  w3 *= w4;
  /* #13: @2 = (@2+@3) */
  w2 += w3;
  /* #14: @0 = (@0+@2) */
  w0 += w2;
  /* #15: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* inv_left:(i0)->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = tan(@1) */
  w2 = tan( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #5: @3 = -0.16113 */
  w3 = -1.6113000000000000e-01;
  /* #6: @1 = tan(@1) */
  w1 = tan( w1 );
  /* #7: @3 = (@3*@1) */
  w3 *= w1;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @0 = (@0/@2) */
  w0 /= w2;
  /* #10: @0 = atan(@0) */
  w0 = atan( w0 );
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd3_motor_reference:(i0[3],out_o0[1x1,0nz],fwd_i0[3x3])->(fwd_o0[1x3]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, w5, w6, w7, w8, w9, w10;
  /* #0: @0 = 0.0190737 */
  w0 = 1.9073704609351459e-02;
  /* #1: @1 = input[2][0] */
  casadi_copy(arg[2], 3, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: @3 = 0.10007 */
  w3 = 1.0007019123296242e-01;
  /* #5: @4 = input[0][0] */
  casadi_copy(arg[0], 3, w4);
  /* #6: @5 = @4[1] */
  for (rr=(&w5), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #7: @6 = (2.*@5) */
  w6 = (2.* w5 );
  /* #8: @7 = @1[1] */
  for (rr=(&w7), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #9: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #10: @8 = @4[2] */
  for (rr=(&w8), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #11: @9 = (2.*@8) */
  w9 = (2.* w8 );
  /* #12: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #13: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #14: @7 = (@7+@10) */
  w7 += w10;
  /* #15: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #16: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #17: @5 = (@5+@8) */
  w5 += w8;
  /* #18: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #19: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #20: @7 = (@7/@5) */
  w7 /= w5;
  /* #21: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #22: @2 = (@2+@7) */
  w2 += w7;
  /* #23: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #24: @1 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+3 : 0, 3, w1);
  /* #25: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #26: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #27: @7 = @1[1] */
  for (rr=(&w7), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #28: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #29: @8 = @1[2] */
  for (rr=(&w8), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #30: @8 = (@9*@8) */
  w8  = (w9*w8);
  /* #31: @7 = (@7+@8) */
  w7 += w8;
  /* #32: @7 = (@7/@5) */
  w7 /= w5;
  /* #33: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #34: @2 = (@2+@7) */
  w2 += w7;
  /* #35: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #36: @1 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+6 : 0, 3, w1);
  /* #37: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #38: @0 = (@0*@2) */
  w0 *= w2;
  /* #39: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #40: @6 = (@6*@2) */
  w6 *= w2;
  /* #41: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #42: @9 = (@9*@2) */
  w9 *= w2;
  /* #43: @6 = (@6+@9) */
  w6 += w9;
  /* #44: @6 = (@6/@5) */
  w6 /= w5;
  /* #45: @3 = (@3*@6) */
  w3 *= w6;
  /* #46: @0 = (@0+@3) */
  w0 += w3;
  /* #47: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

/* fwd1_inv_right:(i0,out_o0[1x1,0nz],fwd_i0)->(fwd_o0) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #5: @3 = (@1/@3) */
  w3  = (w1/w3);
  /* #6: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #7: @4 = 0.24477 */
  w4 = 2.4476999999999999e-01;
  /* #8: @5 = 0.16113 */
  w5 = 1.6113000000000000e-01;
  /* #9: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #10: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #11: @4 = (@4+@6) */
  w4 += w6;
  /* #12: @3 = (@3/@4) */
  w3 /= w4;
  /* #13: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #14: @0 = (@0*@6) */
  w0 *= w6;
  /* #15: @0 = (@0/@4) */
  w0 /= w4;
  /* #16: @4 = (@0/@4) */
  w4  = (w0/w4);
  /* #17: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #18: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #19: @1 = (@1/@2) */
  w1 /= w2;
  /* #20: @5 = (@5*@1) */
  w5 *= w1;
  /* #21: @4 = (@4*@5) */
  w4 *= w5;
  /* #22: @3 = (@3-@4) */
  w3 -= w4;
  /* #23: @4 = 1 */
  w4 = 1.;
  /* #24: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #25: @4 = (@4+@0) */
  w4 += w0;
  /* #26: @3 = (@3/@4) */
  w3 /= w4;
  /* #27: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd1_inv_left:(i0,out_o0[1x1,0nz],fwd_i0)->(fwd_o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #5: @3 = (@1/@3) */
  w3  = (w1/w3);
  /* #6: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #7: @4 = 0.24477 */
  w4 = 2.4476999999999999e-01;
  /* #8: @5 = -0.16113 */
  w5 = -1.6113000000000000e-01;
  /* #9: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #10: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #11: @4 = (@4+@6) */
  w4 += w6;
  /* #12: @3 = (@3/@4) */
  w3 /= w4;
  /* #13: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #14: @0 = (@0*@6) */
  w0 *= w6;
  /* #15: @0 = (@0/@4) */
  w0 /= w4;
  /* #16: @4 = (@0/@4) */
  w4  = (w0/w4);
  /* #17: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #18: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #19: @1 = (@1/@2) */
  w1 /= w2;
  /* #20: @5 = (@5*@1) */
  w5 *= w1;
  /* #21: @4 = (@4*@5) */
  w4 *= w5;
  /* #22: @3 = (@3-@4) */
  w3 -= w4;
  /* #23: @4 = 1 */
  w4 = 1.;
  /* #24: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #25: @4 = (@4+@0) */
  w4 += w0;
  /* #26: @3 = (@3/@4) */
  w3 /= w4;
  /* #27: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd1_jac_inv_right:(i0,out_o0[1x1,0nz],out_jac_o0_i0[1x1,0nz],fwd_i0,fwd_out_o0[1x1,0nz])->(fwd_jac_o0_i0) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @4 = (@0/@3) */
  w4  = (w0/w3);
  /* #5: @3 = (@4/@3) */
  w3  = (w4/w3);
  /* #6: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #7: @5 = sin(@1) */
  w5 = sin( w1 );
  /* #8: @6 = input[3][0] */
  w6 = arg[3] ? arg[3][0] : 0;
  /* #9: @5 = (@5*@6) */
  w5 *= w6;
  /* #10: @2 = (@2*@5) */
  w2 *= w5;
  /* #11: @3 = (@3*@2) */
  w3 *= w2;
  /* #12: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #13: @5 = 0.16113 */
  w5 = 1.6113000000000000e-01;
  /* #14: @7 = tan(@1) */
  w7 = tan( w1 );
  /* #15: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #16: @2 = (@2+@7) */
  w2 += w7;
  /* #17: @3 = (@3/@2) */
  w3 /= w2;
  /* #18: @4 = (@4/@2) */
  w4 /= w2;
  /* #19: @7 = (@4/@2) */
  w7  = (w4/w2);
  /* #20: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #21: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #22: @8 = (@6/@8) */
  w8  = (w6/w8);
  /* #23: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #24: @7 = (@7*@8) */
  w7 *= w8;
  /* #25: @3 = (@3-@7) */
  w3 -= w7;
  /* #26: @7 = cos(@1) */
  w7 = cos( w1 );
  /* #27: @9 = sq(@7) */
  w9 = casadi_sq( w7 );
  /* #28: @5 = (@5/@9) */
  w5 /= w9;
  /* #29: @10 = cos(@1) */
  w10 = cos( w1 );
  /* #30: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #31: @10 = (@6/@10) */
  w10  = (w6/w10);
  /* #32: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #33: @10 = (@10/@2) */
  w10 /= w2;
  /* #34: @11 = tan(@1) */
  w11 = tan( w1 );
  /* #35: @0 = (@0*@11) */
  w0 *= w11;
  /* #36: @0 = (@0/@2) */
  w0 /= w2;
  /* #37: @11 = (@0/@2) */
  w11  = (w0/w2);
  /* #38: @11 = (@11*@8) */
  w11 *= w8;
  /* #39: @10 = (@10-@11) */
  w10 -= w11;
  /* #40: @11 = (@10/@2) */
  w11  = (w10/w2);
  /* #41: @12 = (@0/@2) */
  w12  = (w0/w2);
  /* #42: @2 = (@12/@2) */
  w2  = (w12/w2);
  /* #43: @2 = (@2*@8) */
  w2 *= w8;
  /* #44: @11 = (@11-@2) */
  w11 -= w2;
  /* #45: @11 = (@5*@11) */
  w11  = (w5*w11);
  /* #46: @9 = (@5/@9) */
  w9  = (w5/w9);
  /* #47: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #48: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #49: @1 = (@1*@6) */
  w1 *= w6;
  /* #50: @7 = (@7*@1) */
  w7 *= w1;
  /* #51: @9 = (@9*@7) */
  w9 *= w7;
  /* #52: @9 = (@12*@9) */
  w9  = (w12*w9);
  /* #53: @11 = (@11+@9) */
  w11 += w9;
  /* #54: @3 = (@3-@11) */
  w3 -= w11;
  /* #55: @11 = 1 */
  w11 = 1.;
  /* #56: @9 = sq(@0) */
  w9 = casadi_sq( w0 );
  /* #57: @11 = (@11+@9) */
  w11 += w9;
  /* #58: @3 = (@3/@11) */
  w3 /= w11;
  /* #59: @12 = (@12*@5) */
  w12 *= w5;
  /* #60: @4 = (@4-@12) */
  w4 -= w12;
  /* #61: @4 = (@4/@11) */
  w4 /= w11;
  /* #62: @4 = (@4/@11) */
  w4 /= w11;
  /* #63: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #64: @0 = (@0*@10) */
  w0 *= w10;
  /* #65: @4 = (@4*@0) */
  w4 *= w0;
  /* #66: @3 = (@3-@4) */
  w3 -= w4;
  /* #67: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd1_jac_inv_left:(i0,out_o0[1x1,0nz],out_jac_o0_i0[1x1,0nz],fwd_i0,fwd_out_o0[1x1,0nz])->(fwd_jac_o0_i0) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @4 = (@0/@3) */
  w4  = (w0/w3);
  /* #5: @3 = (@4/@3) */
  w3  = (w4/w3);
  /* #6: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #7: @5 = sin(@1) */
  w5 = sin( w1 );
  /* #8: @6 = input[3][0] */
  w6 = arg[3] ? arg[3][0] : 0;
  /* #9: @5 = (@5*@6) */
  w5 *= w6;
  /* #10: @2 = (@2*@5) */
  w2 *= w5;
  /* #11: @3 = (@3*@2) */
  w3 *= w2;
  /* #12: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #13: @5 = -0.16113 */
  w5 = -1.6113000000000000e-01;
  /* #14: @7 = tan(@1) */
  w7 = tan( w1 );
  /* #15: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #16: @2 = (@2+@7) */
  w2 += w7;
  /* #17: @3 = (@3/@2) */
  w3 /= w2;
  /* #18: @4 = (@4/@2) */
  w4 /= w2;
  /* #19: @7 = (@4/@2) */
  w7  = (w4/w2);
  /* #20: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #21: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #22: @8 = (@6/@8) */
  w8  = (w6/w8);
  /* #23: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #24: @7 = (@7*@8) */
  w7 *= w8;
  /* #25: @3 = (@3-@7) */
  w3 -= w7;
  /* #26: @7 = cos(@1) */
  w7 = cos( w1 );
  /* #27: @9 = sq(@7) */
  w9 = casadi_sq( w7 );
  /* #28: @5 = (@5/@9) */
  w5 /= w9;
  /* #29: @10 = cos(@1) */
  w10 = cos( w1 );
  /* #30: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #31: @10 = (@6/@10) */
  w10  = (w6/w10);
  /* #32: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #33: @10 = (@10/@2) */
  w10 /= w2;
  /* #34: @11 = tan(@1) */
  w11 = tan( w1 );
  /* #35: @0 = (@0*@11) */
  w0 *= w11;
  /* #36: @0 = (@0/@2) */
  w0 /= w2;
  /* #37: @11 = (@0/@2) */
  w11  = (w0/w2);
  /* #38: @11 = (@11*@8) */
  w11 *= w8;
  /* #39: @10 = (@10-@11) */
  w10 -= w11;
  /* #40: @11 = (@10/@2) */
  w11  = (w10/w2);
  /* #41: @12 = (@0/@2) */
  w12  = (w0/w2);
  /* #42: @2 = (@12/@2) */
  w2  = (w12/w2);
  /* #43: @2 = (@2*@8) */
  w2 *= w8;
  /* #44: @11 = (@11-@2) */
  w11 -= w2;
  /* #45: @11 = (@5*@11) */
  w11  = (w5*w11);
  /* #46: @9 = (@5/@9) */
  w9  = (w5/w9);
  /* #47: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #48: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #49: @1 = (@1*@6) */
  w1 *= w6;
  /* #50: @7 = (@7*@1) */
  w7 *= w1;
  /* #51: @9 = (@9*@7) */
  w9 *= w7;
  /* #52: @9 = (@12*@9) */
  w9  = (w12*w9);
  /* #53: @11 = (@11+@9) */
  w11 += w9;
  /* #54: @3 = (@3-@11) */
  w3 -= w11;
  /* #55: @11 = 1 */
  w11 = 1.;
  /* #56: @9 = sq(@0) */
  w9 = casadi_sq( w0 );
  /* #57: @11 = (@11+@9) */
  w11 += w9;
  /* #58: @3 = (@3/@11) */
  w3 /= w11;
  /* #59: @12 = (@12*@5) */
  w12 *= w5;
  /* #60: @4 = (@4-@12) */
  w4 -= w12;
  /* #61: @4 = (@4/@11) */
  w4 /= w11;
  /* #62: @4 = (@4/@11) */
  w4 /= w11;
  /* #63: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #64: @0 = (@0*@10) */
  w0 *= w10;
  /* #65: @4 = (@4*@0) */
  w4 *= w0;
  /* #66: @3 = (@3-@4) */
  w3 -= w4;
  /* #67: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd2_adj1_motor_reference:(i0[3],out_o0[1x1,0nz],adj_o0,out_adj_i0[3x1,0nz],fwd_i0[3x2],fwd_out_o0[1x2,0nz],fwd_adj_o0[1x2])->(fwd_adj_i0[3x2]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, *w3=w+5, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = 0.10007 */
  w1 = 1.0007019123296242e-01;
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #4: @3 = input[0][0] */
  casadi_copy(arg[0], 3, w3);
  /* #5: @4 = @3[1] */
  for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #6: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #7: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #8: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #9: @5 = (@5+@7) */
  w5 += w7;
  /* #10: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #11: @7 = (2.*@5) */
  w7 = (2.* w5 );
  /* #12: @2 = (@2/@7) */
  w2 /= w7;
  /* #13: @3 = input[4][0] */
  casadi_copy(arg[4], 3, w3);
  /* #14: @8 = @3[2] */
  for (rr=(&w8), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #15: @9 = (2.*@8) */
  w9 = (2.* w8 );
  /* #16: @9 = (@2*@9) */
  w9  = (w2*w9);
  /* #17: @10 = (2.*@6) */
  w10 = (2.* w6 );
  /* #18: @11 = input[6][0] */
  w11 = arg[6] ? arg[6][0] : 0;
  /* #19: @12 = (@1*@11) */
  w12  = (w1*w11);
  /* #20: @12 = (@12/@7) */
  w12 /= w7;
  /* #21: @13 = (@2/@7) */
  w13  = (w2/w7);
  /* #22: @14 = (2.*@4) */
  w14 = (2.* w4 );
  /* #23: @15 = @3[1] */
  for (rr=(&w15), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #24: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #25: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #26: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #27: @16 = (@16+@8) */
  w16 += w8;
  /* #28: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #29: @16 = (@16/@5) */
  w16 /= w5;
  /* #30: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #31: @16 = (@13*@16) */
  w16  = (w13*w16);
  /* #32: @12 = (@12-@16) */
  w12 -= w16;
  /* #33: @16 = (@10*@12) */
  w16  = (w10*w12);
  /* #34: @9 = (@9+@16) */
  w9 += w16;
  /* #35: (@0[2] += @9) */
  for (rr=w0+2, ss=(&w9); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #36: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #37: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #38: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #39: @12 = (@4*@12) */
  w12  = (w4*w12);
  /* #40: @15 = (@15+@12) */
  w15 += w12;
  /* #41: (@0[1] += @15) */
  for (rr=w0+1, ss=(&w15); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #42: @15 = 0.0190737 */
  w15 = 1.9073704609351459e-02;
  /* #43: @11 = (@15*@11) */
  w11  = (w15*w11);
  /* #44: (@0[0] += @11) */
  for (rr=w0+0, ss=(&w11); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #45: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #46: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #47: @3 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+3 : 0, 3, w3);
  /* #48: @11 = @3[2] */
  for (rr=(&w11), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #49: @12 = (2.*@11) */
  w12 = (2.* w11 );
  /* #50: @12 = (@2*@12) */
  w12  = (w2*w12);
  /* #51: @9 = input[6][1] */
  w9 = arg[6] ? arg[6][1] : 0;
  /* #52: @1 = (@1*@9) */
  w1 *= w9;
  /* #53: @1 = (@1/@7) */
  w1 /= w7;
  /* #54: @7 = @3[1] */
  for (rr=(&w7), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #55: @14 = (@14*@7) */
  w14 *= w7;
  /* #56: @6 = (@6*@11) */
  w6 *= w11;
  /* #57: @14 = (@14+@6) */
  w14 += w6;
  /* #58: @14 = (@14/@5) */
  w14 /= w5;
  /* #59: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #60: @13 = (@13*@14) */
  w13 *= w14;
  /* #61: @1 = (@1-@13) */
  w1 -= w13;
  /* #62: @10 = (@10*@1) */
  w10 *= w1;
  /* #63: @12 = (@12+@10) */
  w12 += w10;
  /* #64: (@0[2] += @12) */
  for (rr=w0+2, ss=(&w12); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #65: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #66: @2 = (@2*@7) */
  w2 *= w7;
  /* #67: @4 = (@4*@1) */
  w4 *= w1;
  /* #68: @2 = (@2+@4) */
  w2 += w4;
  /* #69: (@0[1] += @2) */
  for (rr=w0+1, ss=(&w2); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #70: @15 = (@15*@9) */
  w15 *= w9;
  /* #71: (@0[0] += @15) */
  for (rr=w0+0, ss=(&w15); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #72: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  return 0;
}

/* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess:(i0[26],i1[7],i2[6],i3[],i4[])->(o0[6],o1[33x6,12nz],o2[33x33,6nz],o3[6x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+5, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real *w0=w+21, w1, w2, *w3=w+49, w4, *w5=w+57, w6, w7, w8, *w9=w+63, *w11=w+75, *w12=w+103, *w13=w+107, *w14=w+111, w15, w16, w17, *w18=w+117, *w19=w+120, w20, w21, w22, *w23=w+132, *w24=w+137, *w25=w+142, *w26=w+148, *w27=w+154, *w28=w+186, *w29=w+193, *w31=w+218, *w33=w+220, *w34=w+226, *w35=w+252;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 26, w0);
  /* #1: @1 = @0[13] */
  for (rr=(&w1), ss=w0+13; ss!=w0+14; ss+=1) *rr++ = *ss;
  /* #2: @2 = inv_right(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #4: @3 = input[1][0] */
  casadi_copy(arg[1], 7, w3);
  /* #5: @2 = @3[1] */
  for (rr=(&w2), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #6: @4 = @0[14] */
  for (rr=(&w4), ss=w0+14; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #7: @5 = horzcat(@2, @1, @4) */
  rr=w5;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w4;
  /* #8: @5 = @5' */
  /* #9: @4 = motor_reference(@5) */
  arg1[0]=w5;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #11: @4 = @3[3] */
  for (rr=(&w4), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #12: @6 = inv_left(@4) */
  arg1[0]=(&w4);
  res1[0]=(&w6);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @7 = @3[0] */
  for (rr=(&w7), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #14: @8 = inv_right(@7) */
  arg1[0]=(&w7);
  res1[0]=(&w8);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #15: @6 = (@6-@8) */
  w6 -= w8;
  /* #16: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #17: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #18: @2 = (@2-@6) */
  w2 -= w6;
  /* #19: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #20: @2 = @3[4] */
  for (rr=(&w2), ss=w3+4; ss!=w3+5; ss+=1) *rr++ = *ss;
  /* #21: @6 = (@6-@2) */
  w6 -= w2;
  /* #22: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #23: @6 = @3[5] */
  for (rr=(&w6), ss=w3+5; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #24: @2 = (@2-@6) */
  w2 -= w6;
  /* #25: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #26: @9 = zeros(33x6,12nz) */
  casadi_clear(w9, 12);
  /* #27: @10 = 00 */
  /* #28: @11 = ones(33x1,28nz) */
  casadi_fill(w11, 28, 1.);
  /* #29: {@12, NULL} = vertsplit(@11) */
  casadi_copy(w11, 4, w12);
  /* #30: @2 = @12[1] */
  for (rr=(&w2), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #31: @6 = horzcat(@2, @10, @10) */
  rr=(&w6);
  *rr++ = w2;
  /* #32: @6 = @6' */
  /* #33: @13 = ones(33x1,4nz) */
  casadi_fill(w13, 4, 1.);
  /* #34: {@14, @8} = vertsplit(@13) */
  casadi_copy(w13, 3, w14);
  w8 = w13[3];
  /* #35: @15 = @8[0] */
  for (rr=(&w15), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #36: @8 = horzcat(@10, @15, @10) */
  rr=(&w8);
  *rr++ = w15;
  /* #37: @8 = @8' */
  /* #38: @16 = ones(33x1,1nz) */
  w16 = 1.;
  /* #39: {NULL, @17} = vertsplit(@16) */
  w17 = w16;
  /* #40: @16 = @17[0] */
  for (rr=(&w16), ss=(&w17)+0; ss!=(&w17)+1; ss+=1) *rr++ = *ss;
  /* #41: @17 = horzcat(@10, @10, @16) */
  rr=(&w17);
  *rr++ = w16;
  /* #42: @17 = @17' */
  /* #43: @18 = horzcat(@6, @8, @17) */
  rr=w18;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w17;
  /* #44: @19 = dense(@18) */
  casadi_densify(w18, casadi_s0, w19, 0);
  /* #45: @18 = fwd3_motor_reference(@5, @10, @19) */
  arg1[0]=w5;
  arg1[1]=0;
  arg1[2]=w19;
  res1[0]=w18;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #46: {@6, @8, @16} = horzsplit(@18) */
  w6 = w18[0];
  w8 = w18[1];
  w16 = w18[2];
  /* #47: @20 = @12[0] */
  for (rr=(&w20), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #48: @21 = fwd1_inv_right(@7, @10, @20) */
  arg1[0]=(&w7);
  arg1[1]=0;
  arg1[2]=(&w20);
  res1[0]=(&w21);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #49: @21 = (-@21) */
  w21 = (- w21 );
  /* #50: @20 = @12[2] */
  for (rr=(&w20), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #51: @22 = (-@20) */
  w22 = (- w20 );
  /* #52: @23 = vertcat(@10, @6, @21, @2, @22, @20) */
  rr=w23;
  *rr++ = w6;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w22;
  *rr++ = w20;
  /* #53: @24 = @23[:5] */
  for (rr=w24, ss=w23+0; ss!=w23+5; ss+=1) *rr++ = *ss;
  /* #54: (@9[1, 4, 6, 9, 10] = @24) */
  for (cii=casadi_s1, rr=w9, ss=w24; cii!=casadi_s1+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #55: @6 = fwd1_inv_right(@1, @10, @15) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w15);
  res1[0]=(&w6);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #56: @15 = @14[1] */
  for (rr=(&w15), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #57: @21 = fwd1_inv_left(@4, @10, @15) */
  arg1[0]=(&w4);
  arg1[1]=0;
  arg1[2]=(&w15);
  res1[0]=(&w21);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #58: @15 = @14[0] */
  for (rr=(&w15), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #59: @2 = (-@15) */
  w2 = (- w15 );
  /* #60: @22 = @14[2] */
  for (rr=(&w22), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #61: @22 = (-@22) */
  w22 = (- w22 );
  /* #62: @25 = vertcat(@6, @8, @21, @2, @15, @22) */
  rr=w25;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w15;
  *rr++ = w22;
  /* #63: (@9[0, 2, 5, 7, 8, 11] = @25) */
  for (cii=casadi_s2, rr=w9, ss=w25; cii!=casadi_s2+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #64: (@9[3] = @16) */
  for (rr=w9+3, ss=(&w16); rr!=w9+4; rr+=1) *rr = *ss++;
  /* #65: output[1][0] = @9 */
  casadi_copy(w9, 12, res[1]);
  /* #66: @25 = zeros(33x33,6nz) */
  casadi_clear(w25, 6);
  /* #67: @3 = zeros(7x1) */
  casadi_clear(w3, 7);
  /* #68: @26 = input[2][0] */
  casadi_copy(arg[2], 6, w26);
  /* #69: {@16, @6, @8, NULL, NULL, NULL} = vertsplit(@26) */
  w16 = w26[0];
  w6 = w26[1];
  w8 = w26[2];
  /* #70: @27 = ones(33x1,32nz) */
  casadi_fill(w27, 32, 1.);
  /* #71: {@28, @29} = vertsplit(@27) */
  casadi_copy(w27, 7, w28);
  casadi_copy(w27+7, 25, w29);
  /* #72: @21 = @28[0] */
  for (rr=(&w21), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #73: @2 = fwd1_jac_inv_right(@7, @10, @10, @21, @10) */
  arg1[0]=(&w7);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  res1[0]=(&w2);
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #74: @2 = (@8*@2) */
  w2  = (w8*w2);
  /* #75: @2 = (-@2) */
  w2 = (- w2 );
  /* #76: (@3[0] += @2) */
  for (rr=w3+0, ss=(&w2); rr!=w3+1; rr+=1) *rr += *ss++;
  /* #77: @2 = @28[3] */
  for (rr=(&w2), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #78: @7 = fwd1_jac_inv_left(@4, @10, @10, @2, @10) */
  arg1[0]=(&w4);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w2);
  arg1[4]=0;
  res1[0]=(&w7);
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #79: @8 = (@8*@7) */
  w8 *= w7;
  /* #80: (@3[3] += @8) */
  for (rr=w3+3, ss=(&w8); rr!=w3+4; rr+=1) *rr += *ss++;
  /* #81: @30 = zeros(3x1,0nz) */
  /* #82: @8 = @28[1] */
  for (rr=(&w8), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #83: @7 = @29[13] */
  for (rr=(&w7), ss=w29+13; ss!=w29+14; ss+=1) *rr++ = *ss;
  /* #84: @31 = horzcat(@8, @7, @10) */
  rr=w31;
  *rr++ = w8;
  *rr++ = w7;
  /* #85: @31 = @31' */
  /* #86: @14 = horzcat(@31, @17) */
  rr=w14;
  for (i=0, cs=w31; i<2; ++i) *rr++ = *cs++;
  *rr++ = w17;
  /* #87: @26 = dense(@14) */
  casadi_densify(w14, casadi_s3, w26, 0);
  /* #88: @32 = zeros(1x2,0nz) */
  /* #89: @31 = zeros(1x2) */
  casadi_clear(w31, 2);
  /* #90: @33 = fwd2_adj1_motor_reference(@5, @10, @6, @30, @26, @32, @31) */
  arg1[0]=w5;
  arg1[1]=0;
  arg1[2]=(&w6);
  arg1[3]=0;
  arg1[4]=w26;
  arg1[5]=0;
  arg1[6]=w31;
  res1[0]=w33;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #91: {@5, @14} = horzsplit(@33) */
  casadi_copy(w33, 3, w5);
  casadi_copy(w33+3, 3, w14);
  /* #92: @5 = @5' */
  /* #93: {@6, @17, @8} = horzsplit(@5) */
  w6 = w5[0];
  w17 = w5[1];
  w8 = w5[2];
  /* #94: (@3[1] += @6) */
  for (rr=w3+1, ss=(&w6); rr!=w3+2; rr+=1) *rr += *ss++;
  /* #95: @0 = zeros(26x1) */
  casadi_clear(w0, 26);
  /* #96: @34 = @0; (@34[14] += @8) */
  casadi_copy(w0, 26, w34);
  for (rr=w34+14, ss=(&w8); rr!=w34+15; rr+=1) *rr += *ss++;
  /* #97: (@34[13] += @17) */
  for (rr=w34+13, ss=(&w17); rr!=w34+14; rr+=1) *rr += *ss++;
  /* #98: @17 = fwd1_jac_inv_right(@1, @10, @10, @7, @10) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w7);
  arg1[4]=0;
  res1[0]=(&w17);
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #99: @16 = (@16*@17) */
  w16 *= w17;
  /* #100: (@34[13] += @16) */
  for (rr=w34+13, ss=(&w16); rr!=w34+14; rr+=1) *rr += *ss++;
  /* #101: @35 = vertcat(@3, @34) */
  rr=w35;
  for (i=0, cs=w3; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<26; ++i) *rr++ = *cs++;
  /* #102: @12 = @35[0, 3, 20, 21] */
  for (cii=casadi_s4, rr=w12, ss=w35; cii!=casadi_s4+4; ++cii) *rr++ = ss[*cii];
  /* #103: (@25[0, 1, 2, 4] = @12) */
  for (cii=casadi_s5, rr=w25, ss=w12; cii!=casadi_s5+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #104: @14 = @14' */
  /* #105: {NULL, @16, @17} = horzsplit(@14) */
  w16 = w14[1];
  w17 = w14[2];
  /* #106: (@0[14] += @17) */
  for (rr=w0+14, ss=(&w17); rr!=w0+15; rr+=1) *rr += *ss++;
  /* #107: (@0[13] += @16) */
  for (rr=w0+13, ss=(&w16); rr!=w0+14; rr+=1) *rr += *ss++;
  /* #108: @31 = @0[13:15] */
  for (rr=w31, ss=w0+13; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #109: (@25[3:7:2] = @31) */
  for (rr=w25+3, ss=w31; rr!=w25+7; rr+=2) *rr = *ss++;
  /* #110: @33 = @25' */
  casadi_trans(w25,casadi_s6, w33, casadi_s6, iw);
  /* #111: output[2][0] = @33 */
  casadi_copy(w33, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s11;
    case 2: return casadi_s6;
    case 3: return casadi_s12;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 34;
  if (sz_w) *sz_w = 285;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_constr_h_fun_jac_uxt_zt_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 11*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 34*sizeof(casadi_int);
  if (sz_w) *sz_w = 285*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
