/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c11 CASADI_PREFIX(c11)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[2] = {0, 28};
static const casadi_int casadi_s1[1] = {2};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 30};
static const casadi_int casadi_s5[1] = {3};
static const casadi_int casadi_s6[2] = {0, 26};
static const casadi_int casadi_s7[2] = {0, 24};
static const casadi_int casadi_s8[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s9[4] = {0, 7, 8, 19};
static const casadi_int casadi_s10[4] = {0, 1, 4, 7};
static const casadi_int casadi_s11[5] = {2, 1, 0, 1, 1};
static const casadi_int casadi_s12[3] = {0, 1, 12};
static const casadi_int casadi_s13[46] = {33, 33, 0, 1, 1, 1, 1, 1, 1, 1, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 7, 8, 19, 7, 8, 19, 7, 8, 19};
static const casadi_int casadi_s14[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static const casadi_int casadi_s15[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s16[4] = {0, 1, 0, 0};
static const casadi_int casadi_s17[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s18[37] = {33, 1, 0, 33, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32};
static const casadi_int casadi_s19[3] = {0, 0, 0};
static const casadi_int casadi_s20[36] = {0, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[28] = {0., 0., 0., 2.0667941717248488e+00, 3.1001912575872730e+00, 4.1335883434496976e+00, 5.1669854293121222e+00, 6.2003825151745460e+00, 7.2337796010369706e+00, 8.2671766868993952e+00, 9.3005737727618190e+00, 1.0333970858624244e+01, 1.1367367944486668e+01, 1.2400765030349092e+01, 1.3434162116211517e+01, 1.4467559202073941e+01, 1.5500956287936367e+01, 1.6534353373798790e+01, 1.7567750459661216e+01, 1.8601147545523638e+01, 1.9634544631386063e+01, 2.0667941717248489e+01, 2.1701338803110911e+01, 2.2734735888973336e+01, 2.3768132974835762e+01, 2.5834927146560609e+01, 2.5834927146560609e+01, 2.5834927146560609e+01};
static const casadi_real casadi_c1[25] = {6.5443756480842052e-01, 9.2943035689597087e-01, 6.9510141057043140e-01, 7.7975352210089666e-01, 9.1053199132018570e-01, 4.0471754811644356e-01, -1.1557994616646283e-01, -7.2228738328437236e-01, -9.1527221933827718e-01, -6.5030371297517964e-01, -8.2692262294871433e-01, -7.9412905853161941e-01, -7.2672155451214682e-01, -7.9412905853161542e-01, -8.2692262294872054e-01, -6.5030371297517164e-01, -9.1527221933828429e-01, -7.2228738328437503e-01, -1.1557994616645040e-01, 4.0471754811644534e-01, 9.1053199132018081e-01, 7.7975352210089932e-01, 6.9510141057042851e-01, 9.2943035689597120e-01, 6.5443756480843951e-01};
static const casadi_real casadi_c2[25] = {4.1663687796189852e-01, 1.2665917233411434e+00, 5.0688521992966962e-01, -3.2779268158395936e-01, -9.5080199516552522e-01, -7.7730276165019518e-01, -6.8266427365053373e-01, -9.1105947854467284e-01, -7.5534817312963543e-01, 1.2777970274869821e-01, 8.7596020136519637e-01, 8.4114041055290056e-01, 6.7965523173592857e-01, 8.4114041055289746e-01, 8.7596020136519637e-01, 1.2777970274870309e-01, -7.5534817312963209e-01, -9.1105947854467706e-01, -6.8266427365053495e-01, -7.7730276165019041e-01, -9.5080199516552744e-01, -3.2779268158396180e-01, 5.0688521992966851e-01, 1.2665917233411457e+00, 4.1663687796190807e-01};
static const casadi_real casadi_c3[30] = {0., 0., 0., 0., 2.0667941717248488e+00, 3.1001912575872730e+00, 4.1335883434496976e+00, 5.1669854293121222e+00, 6.2003825151745460e+00, 7.2337796010369706e+00, 8.2671766868993952e+00, 9.3005737727618190e+00, 1.0333970858624244e+01, 1.1367367944486668e+01, 1.2400765030349092e+01, 1.3434162116211517e+01, 1.4467559202073941e+01, 1.5500956287936367e+01, 1.6534353373798790e+01, 1.7567750459661216e+01, 1.8601147545523638e+01, 1.9634544631386063e+01, 2.0667941717248489e+01, 2.1701338803110911e+01, 2.2734735888973336e+01, 2.3768132974835762e+01, 2.5834927146560609e+01, 2.5834927146560609e+01, 2.5834927146560609e+01, 2.5834927146560609e+01};
static const casadi_real casadi_c4[26] = {6.6996477657936486e-05, 2.8710122017675427e-01, 1.5959934160549578e+00, 2.2944116949110307e+00, 1.9556716929951374e+00, 9.7311568195890474e-01, 1.6985327323677846e-01, -5.3560999777607166e-01, -1.4770962079514764e+00, -2.2576708088751478e+00, -2.1256236364222763e+00, -1.2204089170000199e+00, -3.5117686793352915e-01, 3.5117686793353009e-01, 1.2204089170000181e+00, 2.1256236364222745e+00, 2.2576708088751509e+00, 1.4770962079514836e+00, 5.3560999777607443e-01, -1.6985327323677701e-01, -9.7311568195889842e-01, -1.9556716929951332e+00, -2.2944116949110289e+00, -1.5959934160549576e+00, -2.8710122017675171e-01, -6.6996477649022989e-05};
static const casadi_real casadi_c5[26] = {3.3968943834347052e-04, 4.5120227100629234e-01, 1.4116728933346616e+00, 2.3694272560844540e+00, 3.1752222735144824e+00, 4.1161633799292723e+00, 4.5343973147501906e+00, 4.4149573351976326e+00, 3.6685476581563661e+00, 2.7227080139213569e+00, 2.0506860520072920e+00, 1.1961466232183784e+00, 3.7549596833313215e-01, -3.7549596833313126e-01, -1.1961466232183737e+00, -2.0506860520072938e+00, -2.7227080139213511e+00, -3.6685476581563670e+00, -4.4149573351976361e+00, -4.5343973147501817e+00, -4.1161633799292616e+00, -3.1752222735144766e+00, -2.3694272560844456e+00, -1.4116728933346570e+00, -4.5120227100628735e-01, -3.3968943832575596e-04};
static const casadi_real casadi_c6[26] = {0., 0., 2.0667941717248488e+00, 3.1001912575872730e+00, 4.1335883434496976e+00, 5.1669854293121222e+00, 6.2003825151745460e+00, 7.2337796010369706e+00, 8.2671766868993952e+00, 9.3005737727618190e+00, 1.0333970858624244e+01, 1.1367367944486668e+01, 1.2400765030349092e+01, 1.3434162116211517e+01, 1.4467559202073941e+01, 1.5500956287936367e+01, 1.6534353373798790e+01, 1.7567750459661216e+01, 1.8601147545523638e+01, 1.9634544631386063e+01, 2.0667941717248489e+01, 2.1701338803110911e+01, 2.2734735888973336e+01, 2.3768132974835762e+01, 2.5834927146560609e+01, 2.5834927146560609e+01};
static const casadi_real casadi_c7[24] = {8.2248620303579889e-01, -4.9010299061530566e-01, -8.0770297587693141e-01, -6.0287504397366432e-01, 1.6789212577519108e-01, 9.1579983429777689e-02, -2.2101398196176558e-01, 1.5067906378416784e-01, 8.5458715527663476e-01, 7.2400097586118306e-01, -3.3694492938536658e-02, -1.5626633849291738e-01, 1.5626633849291438e-01, 3.3694492938539655e-02, -7.2400097586117829e-01, -8.5458715527663620e-01, -1.5067906378417517e-01, 2.2101398196176869e-01, -9.1579983429771805e-02, -1.6789212577519785e-01, 6.0287504397366465e-01, 8.0770297587693185e-01, 4.9010299061530782e-01, -8.2248620303579223e-01};
static const casadi_real casadi_c8[24] = {2.6610563920649566e-01, -1.5117063874820824e-01, 8.1916344344844516e-02, 1.2655200117014798e-01, -4.8946765006755694e-01, -5.0348264128177878e-01, -5.8710000774927673e-01, -1.8674799715817747e-01, 2.5640531600877048e-01, -1.7091098125764193e-01, 3.1733749655125987e-02, 6.5229044035108208e-02, -6.5229044035104322e-02, -3.1733749655135868e-02, 1.7091098125765569e-01, -2.5640531600878513e-01, 1.8674799715818180e-01, 5.8710000774929194e-01, 5.0348264128176778e-01, 4.8946765006755072e-01, -1.2655200117014076e-01, -8.1916344344849845e-02, 1.5117063874821030e-01, -2.6610563920647778e-01};
static const casadi_real casadi_c9[24] = {0., 2.0667941717248488e+00, 3.1001912575872730e+00, 4.1335883434496976e+00, 5.1669854293121222e+00, 6.2003825151745460e+00, 7.2337796010369706e+00, 8.2671766868993952e+00, 9.3005737727618190e+00, 1.0333970858624244e+01, 1.1367367944486668e+01, 1.2400765030349092e+01, 1.3434162116211517e+01, 1.4467559202073941e+01, 1.5500956287936367e+01, 1.6534353373798790e+01, 1.7567750459661216e+01, 1.8601147545523638e+01, 1.9634544631386063e+01, 2.0667941717248489e+01, 2.1701338803110911e+01, 2.2734735888973336e+01, 2.3768132974835762e+01, 2.5834927146560609e+01};
static const casadi_real casadi_c10[23] = {-6.3508462120138431e-01, -3.0733586305458938e-01, 1.9820835059964137e-01, 7.4585769622681819e-01, -7.3845904337660223e-02, -3.0249162656643941e-01, 3.5968075663357990e-01, 6.8115935405896655e-01, -1.2636592574331718e-01, -7.3320844345848268e-01, -1.1861059725370536e-01, 3.0243231886512090e-01, -1.1861059725369957e-01, -7.3320844345847980e-01, -1.2636592574332350e-01, 6.8115935405895967e-01, 3.5968075663359089e-01, -3.0249162656643647e-01, -7.3845904337672338e-02, 7.4585769622682685e-01, 1.9820835059964126e-01, -3.0733586305458732e-01, -6.3508462120138254e-01};
static const casadi_real casadi_c11[23] = {-2.0189542029067403e-01, 2.2555413236774266e-01, 4.3193132084413263e-02, -5.9611127190629143e-01, -1.3562057998765864e-02, -8.0915039931349186e-02, 3.8741352774087257e-01, 4.2883158780839159e-01, -4.1350638889192720e-01, 1.9609570578927105e-01, 3.2412801272831790e-02, -1.2624197402428150e-01, 3.2412801272818467e-02, 1.9609570578929358e-01, -4.1350638889195540e-01, 4.2883158780840924e-01, 3.8741352774088400e-01, -8.0915039931374499e-02, -1.3562057998761201e-02, -5.9611127190627988e-01, 4.3193132084401092e-02, 2.2555413236774952e-01, -2.0189542029066654e-01};

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c4,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* inv_right:(i0)->(o0) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = tan(@1) */
  w2 = tan( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #5: @3 = 0.16113 */
  w3 = 1.6113000000000000e-01;
  /* #6: @1 = tan(@1) */
  w1 = tan( w1 );
  /* #7: @3 = (@3*@1) */
  w3 *= w1;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @0 = (@0/@2) */
  w0 /= w2;
  /* #10: @0 = atan(@0) */
  w0 = atan( w0 );
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* jac_inv_right:(i0,out_o0[1x1,0nz])->(jac_o0_i0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #4: @2 = (@0/@2) */
  w2  = (w0/w2);
  /* #5: @3 = 0.24477 */
  w3 = 2.4476999999999999e-01;
  /* #6: @4 = 0.16113 */
  w4 = 1.6113000000000000e-01;
  /* #7: @5 = tan(@1) */
  w5 = tan( w1 );
  /* #8: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #9: @3 = (@3+@5) */
  w3 += w5;
  /* #10: @2 = (@2/@3) */
  w2 /= w3;
  /* #11: @5 = tan(@1) */
  w5 = tan( w1 );
  /* #12: @0 = (@0*@5) */
  w0 *= w5;
  /* #13: @0 = (@0/@3) */
  w0 /= w3;
  /* #14: @3 = (@0/@3) */
  w3  = (w0/w3);
  /* #15: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #16: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #17: @4 = (@4/@1) */
  w4 /= w1;
  /* #18: @3 = (@3*@4) */
  w3 *= w4;
  /* #19: @2 = (@2-@3) */
  w2 -= w3;
  /* #20: @3 = 1 */
  w3 = 1.;
  /* #21: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #22: @3 = (@3+@0) */
  w3 += w0;
  /* #23: @2 = (@2/@3) */
  w2 /= w3;
  /* #24: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c7,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c8,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* fwd1_jac_inv_right:(i0,out_o0[1x1,0nz],out_jac_o0_i0[1x1,0nz],fwd_i0,fwd_out_o0[1x1,0nz])->(fwd_jac_o0_i0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @4 = (@0/@3) */
  w4  = (w0/w3);
  /* #5: @3 = (@4/@3) */
  w3  = (w4/w3);
  /* #6: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #7: @5 = sin(@1) */
  w5 = sin( w1 );
  /* #8: @6 = input[3][0] */
  w6 = arg[3] ? arg[3][0] : 0;
  /* #9: @5 = (@5*@6) */
  w5 *= w6;
  /* #10: @2 = (@2*@5) */
  w2 *= w5;
  /* #11: @3 = (@3*@2) */
  w3 *= w2;
  /* #12: @2 = 0.24477 */
  w2 = 2.4476999999999999e-01;
  /* #13: @5 = 0.16113 */
  w5 = 1.6113000000000000e-01;
  /* #14: @7 = tan(@1) */
  w7 = tan( w1 );
  /* #15: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #16: @2 = (@2+@7) */
  w2 += w7;
  /* #17: @3 = (@3/@2) */
  w3 /= w2;
  /* #18: @4 = (@4/@2) */
  w4 /= w2;
  /* #19: @7 = (@4/@2) */
  w7  = (w4/w2);
  /* #20: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #21: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #22: @8 = (@6/@8) */
  w8  = (w6/w8);
  /* #23: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #24: @7 = (@7*@8) */
  w7 *= w8;
  /* #25: @3 = (@3-@7) */
  w3 -= w7;
  /* #26: @7 = cos(@1) */
  w7 = cos( w1 );
  /* #27: @9 = sq(@7) */
  w9 = casadi_sq( w7 );
  /* #28: @5 = (@5/@9) */
  w5 /= w9;
  /* #29: @10 = cos(@1) */
  w10 = cos( w1 );
  /* #30: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #31: @10 = (@6/@10) */
  w10  = (w6/w10);
  /* #32: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #33: @10 = (@10/@2) */
  w10 /= w2;
  /* #34: @11 = tan(@1) */
  w11 = tan( w1 );
  /* #35: @0 = (@0*@11) */
  w0 *= w11;
  /* #36: @0 = (@0/@2) */
  w0 /= w2;
  /* #37: @11 = (@0/@2) */
  w11  = (w0/w2);
  /* #38: @11 = (@11*@8) */
  w11 *= w8;
  /* #39: @10 = (@10-@11) */
  w10 -= w11;
  /* #40: @11 = (@10/@2) */
  w11  = (w10/w2);
  /* #41: @12 = (@0/@2) */
  w12  = (w0/w2);
  /* #42: @2 = (@12/@2) */
  w2  = (w12/w2);
  /* #43: @2 = (@2*@8) */
  w2 *= w8;
  /* #44: @11 = (@11-@2) */
  w11 -= w2;
  /* #45: @11 = (@5*@11) */
  w11  = (w5*w11);
  /* #46: @9 = (@5/@9) */
  w9  = (w5/w9);
  /* #47: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #48: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #49: @1 = (@1*@6) */
  w1 *= w6;
  /* #50: @7 = (@7*@1) */
  w7 *= w1;
  /* #51: @9 = (@9*@7) */
  w9 *= w7;
  /* #52: @9 = (@12*@9) */
  w9  = (w12*w9);
  /* #53: @11 = (@11+@9) */
  w11 += w9;
  /* #54: @3 = (@3-@11) */
  w3 -= w11;
  /* #55: @11 = 1 */
  w11 = 1.;
  /* #56: @9 = sq(@0) */
  w9 = casadi_sq( w0 );
  /* #57: @11 = (@11+@9) */
  w11 += w9;
  /* #58: @3 = (@3/@11) */
  w3 /= w11;
  /* #59: @12 = (@12*@5) */
  w12 *= w5;
  /* #60: @4 = (@4-@12) */
  w4 -= w12;
  /* #61: @4 = (@4/@11) */
  w4 /= w11;
  /* #62: @4 = (@4/@11) */
  w4 /= w11;
  /* #63: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #64: @0 = (@0*@10) */
  w0 *= w10;
  /* #65: @4 = (@4*@0) */
  w4 *= w0;
  /* #66: @3 = (@3-@4) */
  w3 -= w4;
  /* #67: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd1_inv_right:(i0,out_o0[1x1,0nz],fwd_i0)->(fwd_o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = 0.24477 */
  w0 = 2.4476999999999999e-01;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #5: @3 = (@1/@3) */
  w3  = (w1/w3);
  /* #6: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #7: @4 = 0.24477 */
  w4 = 2.4476999999999999e-01;
  /* #8: @5 = 0.16113 */
  w5 = 1.6113000000000000e-01;
  /* #9: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #10: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #11: @4 = (@4+@6) */
  w4 += w6;
  /* #12: @3 = (@3/@4) */
  w3 /= w4;
  /* #13: @6 = tan(@2) */
  w6 = tan( w2 );
  /* #14: @0 = (@0*@6) */
  w0 *= w6;
  /* #15: @0 = (@0/@4) */
  w0 /= w4;
  /* #16: @4 = (@0/@4) */
  w4  = (w0/w4);
  /* #17: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #18: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #19: @1 = (@1/@2) */
  w1 /= w2;
  /* #20: @5 = (@5*@1) */
  w5 *= w1;
  /* #21: @4 = (@4*@5) */
  w4 *= w5;
  /* #22: @3 = (@3-@4) */
  w3 -= w4;
  /* #23: @4 = 1 */
  w4 = 1.;
  /* #24: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #25: @4 = (@4+@0) */
  w4 += w0;
  /* #26: @3 = (@3/@4) */
  w3 /= w4;
  /* #27: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd1_traj:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_traj:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac_f_x) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c7,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac_f_x) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c8,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],out_jac_jac_f_x_x[1x1,0nz],out_jac_jac_f_x_out_f[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac_f_x[1x1,0nz])->(fwd_jac_jac_f_x_x,fwd_jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #2: {@2, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #3: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #4: @3 = BSpline(@1) */
  casadi_clear((&w3), 1);
  CASADI_PREFIX(nd_boor_eval)((&w3),1,casadi_c9,casadi_s7,casadi_s3,casadi_s2,casadi_c10,1,(&w1),casadi_s3, iw, w);
  /* #5: @1 = input[5][0] */
  w1 = arg[5] ? arg[5][0] : 0;
  /* #6: @3 = (@3*@1) */
  w3 *= w1;
  /* #7: @2 = (@2*@3) */
  w2 *= w3;
  /* #8: (@0[0] += @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr += *ss++;
  /* #9: @0 = @0' */
  /* #10: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #11: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* fwd1_jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],out_jac_jac_f_x_x[1x1,0nz],out_jac_jac_f_x_out_f[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac_f_x[1x1,0nz])->(fwd_jac_jac_f_x_x,fwd_jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #2: {@2, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #3: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #4: @3 = BSpline(@1) */
  casadi_clear((&w3), 1);
  CASADI_PREFIX(nd_boor_eval)((&w3),1,casadi_c9,casadi_s7,casadi_s3,casadi_s2,casadi_c11,1,(&w1),casadi_s3, iw, w);
  /* #5: @1 = input[5][0] */
  w1 = arg[5] ? arg[5][0] : 0;
  /* #6: @3 = (@3*@1) */
  w3 *= w1;
  /* #7: @2 = (@2*@3) */
  w2 *= w3;
  /* #8: (@0[0] += @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr += *ss++;
  /* #9: @0 = @0' */
  /* #10: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #11: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess:(i0[26],i1[7],i2[0],i3[0])->(o0,o1[33],o2[33x33,10nz],o3[],o4[0x33]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+5, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4, *cr, *cs;
  casadi_real w0, *w1=w+14, w2, w4, w5, w6, *w7=w+44, w8, *w9=w+47, *w10=w+49, w11, w12, *w13=w+53, w14, w15, w16, w17, *w18=w+64, *w19=w+71, *w20=w+73, *w21=w+75, *w22=w+77, w23, w24, w25, w26, w27, w28, *w29=w+109, *w30=w+119, *w31=w+150, *w32=w+174, *w33=w+207, *w34=w+211, *w36=w+214;
  /* #0: @0 = 50 */
  w0 = 50.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 26, w1);
  /* #2: @2 = @1[12] */
  for (rr=(&w2), ss=w1+12; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #3: @3 = 00 */
  /* #4: @4 = jac_traj(@2, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  res1[0]=(&w4);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #5: @5 = jac_traj(@2, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @6 = (-@5) */
  w6 = (- w5 );
  /* #7: @7 = horzcat(@4, @6) */
  rr=w7;
  *rr++ = w4;
  *rr++ = w6;
  /* #8: @7 = @7' */
  /* #9: @6 = traj(@2) */
  arg1[0]=(&w2);
  res1[0]=(&w6);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @8 = traj(@2) */
  arg1[0]=(&w2);
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @9 = horzcat(@6, @8) */
  rr=w9;
  *rr++ = w6;
  *rr++ = w8;
  /* #12: @9 = @9' */
  /* #13: @6 = @1[0] */
  for (rr=(&w6), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #14: @8 = @1[1] */
  for (rr=(&w8), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #15: @10 = vertcat(@6, @8) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w8;
  /* #16: @9 = (@9-@10) */
  for (i=0, rr=w9, cs=w10; i<2; ++i) (*rr++) -= (*cs++);
  /* #17: @6 = dot(@7, @9) */
  w6 = casadi_dot(2, w7, w9);
  /* #18: @8 = sq(@6) */
  w8 = casadi_sq( w6 );
  /* #19: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #20: @10 = horzcat(@5, @4) */
  rr=w10;
  *rr++ = w5;
  *rr++ = w4;
  /* #21: @10 = @10' */
  /* #22: @11 = dot(@10, @9) */
  w11 = casadi_dot(2, w10, w9);
  /* #23: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #24: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #25: @8 = (@8+@12) */
  w8 += w12;
  /* #26: @12 = 0.0001 */
  w12 = 1.0000000000000000e-04;
  /* #27: @13 = input[1][0] */
  casadi_copy(arg[1], 7, w13);
  /* #28: @14 = @13[0] */
  for (rr=(&w14), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #29: @15 = inv_right(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w15);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #30: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #31: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #32: @8 = (@8+@16) */
  w8 += w16;
  /* #33: @16 = 6 */
  w16 = 6.;
  /* #34: @17 = @13[6] */
  for (rr=(&w17), ss=w13+6; ss!=w13+7; ss+=1) *rr++ = *ss;
  /* #35: @16 = (@16*@17) */
  w16 *= w17;
  /* #36: @8 = (@8-@16) */
  w8 -= w16;
  /* #37: @16 = sq(@14) */
  w16 = casadi_sq( w14 );
  /* #38: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #39: @8 = (@8+@16) */
  w8 += w16;
  /* #40: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #41: @13 = zeros(7x1) */
  casadi_clear(w13, 7);
  /* #42: @8 = (2.*@14) */
  w8 = (2.* w14 );
  /* #43: @8 = (@12*@8) */
  w8  = (w12*w8);
  /* #44: @18 = @13; (@18[0] += @8) */
  casadi_copy(w13, 7, w18);
  for (rr=w18+0, ss=(&w8); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #45: @8 = -6 */
  w8 = -6.;
  /* #46: (@18[6] += @8) */
  for (rr=w18+6, ss=(&w8); rr!=w18+7; rr+=1) *rr += *ss++;
  /* #47: @8 = jac_inv_right(@14, @3) */
  arg1[0]=(&w14);
  arg1[1]=0;
  res1[0]=(&w8);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #48: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #49: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #50: @16 = (@8*@15) */
  w16  = (w8*w15);
  /* #51: (@18[0] += @16) */
  for (rr=w18+0, ss=(&w16); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #52: output[1][0] = @18 */
  casadi_copy(w18, 7, res[1]);
  /* #53: @1 = zeros(26x1) */
  casadi_clear(w1, 26);
  /* #54: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #55: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #56: @19 = (@6*@7) */
  for (i=0, rr=w19, cs=w7; i<2; ++i) (*rr++)  = (w6*(*cs++));
  /* #57: @20 = (-@19) */
  for (i=0, rr=w20, cs=w19; i<2; ++i) *rr++ = (- *cs++ );
  /* #58: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #59: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #60: @21 = (@11*@10) */
  for (i=0, rr=w21, cs=w10; i<2; ++i) (*rr++)  = (w11*(*cs++));
  /* #61: @20 = (@20-@21) */
  for (i=0, rr=w20, cs=w21; i<2; ++i) (*rr++) -= (*cs++);
  /* #62: {@16, @17} = vertsplit(@20) */
  w16 = w20[0];
  w17 = w20[1];
  /* #63: @22 = @1; (@22[1] += @17) */
  casadi_copy(w1, 26, w22);
  for (rr=w22+1, ss=(&w17); rr!=w22+2; rr+=1) *rr += *ss++;
  /* #64: (@22[0] += @16) */
  for (rr=w22+0, ss=(&w16); rr!=w22+1; rr+=1) *rr += *ss++;
  /* #65: @21 = (@21+@19) */
  for (i=0, rr=w21, cs=w19; i<2; ++i) (*rr++) += (*cs++);
  /* #66: @21 = @21' */
  /* #67: {@16, @17} = horzsplit(@21) */
  w16 = w21[0];
  w17 = w21[1];
  /* #68: @23 = (@4*@17) */
  w23  = (w4*w17);
  /* #69: @24 = (@5*@16) */
  w24  = (w5*w16);
  /* #70: @23 = (@23+@24) */
  w23 += w24;
  /* #71: {@24, NULL} = jac_jac_traj(@2, @3, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w24);
  res1[1]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #72: @21 = (@11*@9) */
  for (i=0, rr=w21, cs=w9; i<2; ++i) (*rr++)  = (w11*(*cs++));
  /* #73: @21 = @21' */
  /* #74: {@25, @26} = horzsplit(@21) */
  w25 = w21[0];
  w26 = w21[1];
  /* #75: @21 = (@6*@9) */
  for (i=0, rr=w21, cs=w9; i<2; ++i) (*rr++)  = (w6*(*cs++));
  /* #76: @21 = @21' */
  /* #77: {@27, @28} = horzsplit(@21) */
  w27 = w21[0];
  w28 = w21[1];
  /* #78: @25 = (@25-@28) */
  w25 -= w28;
  /* #79: @28 = (@24*@25) */
  w28  = (w24*w25);
  /* #80: @23 = (@23+@28) */
  w23 += w28;
  /* #81: {@28, NULL} = jac_jac_traj(@2, @3, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w28);
  res1[1]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #82: @26 = (@26+@27) */
  w26 += w27;
  /* #83: @27 = (@28*@26) */
  w27  = (w28*w26);
  /* #84: @23 = (@23+@27) */
  w23 += w27;
  /* #85: (@22[12] += @23) */
  for (rr=w22+12, ss=(&w23); rr!=w22+13; rr+=1) *rr += *ss++;
  /* #86: output[1][1] = @22 */
  if (res[1]) casadi_copy(w22, 26, res[1]+7);
  /* #87: @29 = zeros(33x33,10nz) */
  casadi_clear(w29, 10);
  /* #88: @30 = ones(33x1,31nz) */
  casadi_fill(w30, 31, 1.);
  /* #89: {@18, @31} = vertsplit(@30) */
  casadi_copy(w30, 7, w18);
  casadi_copy(w30+7, 24, w31);
  /* #90: @23 = @18[0] */
  for (rr=(&w23), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #91: @27 = (2.*@23) */
  w27 = (2.* w23 );
  /* #92: @27 = (@12*@27) */
  w27  = (w12*w27);
  /* #93: (@13[0] += @27) */
  for (rr=w13+0, ss=(&w27); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #94: @27 = fwd1_jac_inv_right(@14, @3, @3, @23, @3) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w23);
  arg1[4]=0;
  res1[0]=(&w27);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #95: @15 = (@15*@27) */
  w15 *= w27;
  /* #96: @27 = fwd1_inv_right(@14, @3, @23) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w23);
  res1[0]=(&w27);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #97: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #98: @12 = (@12*@27) */
  w12 *= w27;
  /* #99: @8 = (@8*@12) */
  w8 *= w12;
  /* #100: @15 = (@15+@8) */
  w15 += w8;
  /* #101: (@13[0] += @15) */
  for (rr=w13+0, ss=(&w15); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #102: @15 = project(@10) */
  casadi_sparsify(w10, (&w15), casadi_s8, 0);
  /* #103: @8 = @31[0] */
  for (rr=(&w8), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #104: @12 = vertcat(@8, @3) */
  rr=(&w12);
  *rr++ = w8;
  /* #105: @8 = (-@12) */
  w8 = (- w12 );
  /* #106: @27 = dot(@15, @8) */
  w27 = casadi_dot(1, (&w15), (&w8));
  /* #107: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #108: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #109: @21 = (@10*@27) */
  for (i=0, rr=w21, cr=w10; i<2; ++i) (*rr++)  = ((*cr++)*w27);
  /* #110: @19 = (-@21) */
  for (i=0, rr=w19, cs=w21; i<2; ++i) *rr++ = (- *cs++ );
  /* #111: @15 = project(@7) */
  casadi_sparsify(w7, (&w15), casadi_s8, 0);
  /* #112: @14 = dot(@15, @8) */
  w14 = casadi_dot(1, (&w15), (&w8));
  /* #113: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #114: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #115: @20 = (@7*@14) */
  for (i=0, rr=w20, cr=w7; i<2; ++i) (*rr++)  = ((*cr++)*w14);
  /* #116: @19 = (@19-@20) */
  for (i=0, rr=w19, cs=w20; i<2; ++i) (*rr++) -= (*cs++);
  /* #117: {@15, @8} = vertsplit(@19) */
  w15 = w19[0];
  w8 = w19[1];
  /* #118: @22 = @1; (@22[1] += @8) */
  casadi_copy(w1, 26, w22);
  for (rr=w22+1, ss=(&w8); rr!=w22+2; rr+=1) *rr += *ss++;
  /* #119: (@22[0] += @15) */
  for (rr=w22+0, ss=(&w15); rr!=w22+1; rr+=1) *rr += *ss++;
  /* #120: @21 = (@21+@20) */
  for (i=0, rr=w21, cs=w20; i<2; ++i) (*rr++) += (*cs++);
  /* #121: @21 = @21' */
  /* #122: {@15, @8} = horzsplit(@21) */
  w15 = w21[0];
  w8 = w21[1];
  /* #123: @8 = (@4*@8) */
  w8  = (w4*w8);
  /* #124: @15 = (@5*@15) */
  w15  = (w5*w15);
  /* #125: @8 = (@8+@15) */
  w8 += w15;
  /* #126: @21 = (@9*@27) */
  for (i=0, rr=w21, cr=w9; i<2; ++i) (*rr++)  = ((*cr++)*w27);
  /* #127: @27 = (@11*@12) */
  w27  = (w11*w12);
  /* #128: @27 = (-@27) */
  w27 = (- w27 );
  /* #129: @20 = dense(@27) */
  casadi_densify((&w27), casadi_s8, w20, 0);
  /* #130: @21 = (@21+@20) */
  for (i=0, rr=w21, cs=w20; i<2; ++i) (*rr++) += (*cs++);
  /* #131: @21 = @21' */
  /* #132: {@27, @15} = horzsplit(@21) */
  w27 = w21[0];
  w15 = w21[1];
  /* #133: @21 = (@9*@14) */
  for (i=0, rr=w21, cr=w9; i<2; ++i) (*rr++)  = ((*cr++)*w14);
  /* #134: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #135: @12 = (-@12) */
  w12 = (- w12 );
  /* #136: @20 = dense(@12) */
  casadi_densify((&w12), casadi_s8, w20, 0);
  /* #137: @21 = (@21+@20) */
  for (i=0, rr=w21, cs=w20; i<2; ++i) (*rr++) += (*cs++);
  /* #138: @21 = @21' */
  /* #139: {@12, @14} = horzsplit(@21) */
  w12 = w21[0];
  w14 = w21[1];
  /* #140: @27 = (@27-@14) */
  w27 -= w14;
  /* #141: @27 = (@24*@27) */
  w27  = (w24*w27);
  /* #142: @8 = (@8+@27) */
  w8 += w27;
  /* #143: @15 = (@15+@12) */
  w15 += w12;
  /* #144: @15 = (@28*@15) */
  w15  = (w28*w15);
  /* #145: @8 = (@8+@15) */
  w8 += w15;
  /* #146: (@22[12] += @8) */
  for (rr=w22+12, ss=(&w8); rr!=w22+13; rr+=1) *rr += *ss++;
  /* #147: @32 = vertcat(@13, @22) */
  rr=w32;
  for (i=0, cs=w13; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<26; ++i) *rr++ = *cs++;
  /* #148: @33 = @32[0, 7, 8, 19] */
  for (cii=casadi_s9, rr=w33, ss=w32; cii!=casadi_s9+4; ++cii) *rr++ = ss[*cii];
  /* #149: (@29[:4] = @33) */
  for (rr=w29+0, ss=w33; rr!=w29+4; rr+=1) *rr = *ss++;
  /* #150: (@29[0, 1, 4, 7] = @33) */
  for (cii=casadi_s10, rr=w29, ss=w33; cii!=casadi_s10+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #151: @8 = project(@10) */
  casadi_sparsify(w10, (&w8), casadi_s11, 0);
  /* #152: @15 = ones(33x1,1nz) */
  w15 = 1.;
  /* #153: {NULL, @12} = vertsplit(@15) */
  w12 = w15;
  /* #154: @15 = @12[0] */
  for (rr=(&w15), ss=(&w12)+0; ss!=(&w12)+1; ss+=1) *rr++ = *ss;
  /* #155: @12 = vertcat(@3, @15) */
  rr=(&w12);
  *rr++ = w15;
  /* #156: @15 = (-@12) */
  w15 = (- w12 );
  /* #157: @27 = dot(@8, @15) */
  w27 = casadi_dot(1, (&w8), (&w15));
  /* #158: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #159: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #160: @21 = (@10*@27) */
  for (i=0, rr=w21, cr=w10; i<2; ++i) (*rr++)  = ((*cr++)*w27);
  /* #161: @20 = (-@21) */
  for (i=0, rr=w20, cs=w21; i<2; ++i) *rr++ = (- *cs++ );
  /* #162: @8 = project(@7) */
  casadi_sparsify(w7, (&w8), casadi_s11, 0);
  /* #163: @14 = dot(@8, @15) */
  w14 = casadi_dot(1, (&w8), (&w15));
  /* #164: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #165: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #166: @19 = (@7*@14) */
  for (i=0, rr=w19, cr=w7; i<2; ++i) (*rr++)  = ((*cr++)*w14);
  /* #167: @20 = (@20-@19) */
  for (i=0, rr=w20, cs=w19; i<2; ++i) (*rr++) -= (*cs++);
  /* #168: {@8, @15} = vertsplit(@20) */
  w8 = w20[0];
  w15 = w20[1];
  /* #169: @22 = @1; (@22[1] += @15) */
  casadi_copy(w1, 26, w22);
  for (rr=w22+1, ss=(&w15); rr!=w22+2; rr+=1) *rr += *ss++;
  /* #170: (@22[0] += @8) */
  for (rr=w22+0, ss=(&w8); rr!=w22+1; rr+=1) *rr += *ss++;
  /* #171: @21 = (@21+@19) */
  for (i=0, rr=w21, cs=w19; i<2; ++i) (*rr++) += (*cs++);
  /* #172: @21 = @21' */
  /* #173: {@8, @15} = horzsplit(@21) */
  w8 = w21[0];
  w15 = w21[1];
  /* #174: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #175: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #176: @15 = (@15+@8) */
  w15 += w8;
  /* #177: @21 = (@9*@27) */
  for (i=0, rr=w21, cr=w9; i<2; ++i) (*rr++)  = ((*cr++)*w27);
  /* #178: @27 = (@11*@12) */
  w27  = (w11*w12);
  /* #179: @27 = (-@27) */
  w27 = (- w27 );
  /* #180: @19 = dense(@27) */
  casadi_densify((&w27), casadi_s11, w19, 0);
  /* #181: @21 = (@21+@19) */
  for (i=0, rr=w21, cs=w19; i<2; ++i) (*rr++) += (*cs++);
  /* #182: @21 = @21' */
  /* #183: {@27, @8} = horzsplit(@21) */
  w27 = w21[0];
  w8 = w21[1];
  /* #184: @21 = (@9*@14) */
  for (i=0, rr=w21, cr=w9; i<2; ++i) (*rr++)  = ((*cr++)*w14);
  /* #185: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #186: @12 = (-@12) */
  w12 = (- w12 );
  /* #187: @19 = dense(@12) */
  casadi_densify((&w12), casadi_s11, w19, 0);
  /* #188: @21 = (@21+@19) */
  for (i=0, rr=w21, cs=w19; i<2; ++i) (*rr++) += (*cs++);
  /* #189: @21 = @21' */
  /* #190: {@12, @14} = horzsplit(@21) */
  w12 = w21[0];
  w14 = w21[1];
  /* #191: @27 = (@27-@14) */
  w27 -= w14;
  /* #192: @27 = (@24*@27) */
  w27  = (w24*w27);
  /* #193: @15 = (@15+@27) */
  w15 += w27;
  /* #194: @8 = (@8+@12) */
  w8 += w12;
  /* #195: @8 = (@28*@8) */
  w8  = (w28*w8);
  /* #196: @15 = (@15+@8) */
  w15 += w8;
  /* #197: (@22[12] += @15) */
  for (rr=w22+12, ss=(&w15); rr!=w22+13; rr+=1) *rr += *ss++;
  /* #198: @34 = @22[0, 1, 12] */
  for (cii=casadi_s12, rr=w34, ss=w22; cii!=casadi_s12+3; ++cii) *rr++ = ss[*cii];
  /* #199: (@29[4:7] = @34) */
  for (rr=w29+4, ss=w34; rr!=w29+7; rr+=1) *rr = *ss++;
  /* #200: (@29[2:11:3] = @34) */
  for (rr=w29+2, ss=w34; rr!=w29+11; rr+=3) *rr = *ss++;
  /* #201: @15 = ones(33x1,1nz) */
  w15 = 1.;
  /* #202: {NULL, @8} = vertsplit(@15) */
  w8 = w15;
  /* #203: @15 = @8[0] */
  for (rr=(&w15), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #204: @8 = fwd1_traj(@2, @3, @15) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=(&w15);
  res1[0]=(&w8);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #205: @12 = fwd1_traj(@2, @3, @15) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=(&w15);
  res1[0]=(&w12);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #206: @21 = horzcat(@8, @12) */
  rr=w21;
  *rr++ = w8;
  *rr++ = w12;
  /* #207: @21 = @21' */
  /* #208: @8 = dot(@10, @21) */
  w8 = casadi_dot(2, w10, w21);
  /* #209: @12 = fwd1_jac_traj(@2, @3, @3, @15, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w15);
  arg1[4]=0;
  res1[0]=(&w12);
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #210: @27 = fwd1_jac_traj(@2, @3, @3, @15, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w15);
  arg1[4]=0;
  res1[0]=(&w27);
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #211: @19 = horzcat(@12, @27) */
  rr=w19;
  *rr++ = w12;
  *rr++ = w27;
  /* #212: @19 = @19' */
  /* #213: @14 = dot(@19, @9) */
  w14 = casadi_dot(2, w19, w9);
  /* #214: @8 = (@8+@14) */
  w8 += w14;
  /* #215: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #216: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #217: @10 = (@10*@8) */
  for (i=0, rr=w10; i<2; ++i) (*rr++) *= w8;
  /* #218: @19 = (@11*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w11*(*cs++));
  /* #219: @10 = (@10+@19) */
  for (i=0, rr=w10, cs=w19; i<2; ++i) (*rr++) += (*cs++);
  /* #220: @19 = (-@10) */
  for (i=0, rr=w19, cs=w10; i<2; ++i) *rr++ = (- *cs++ );
  /* #221: @14 = dot(@7, @21) */
  w14 = casadi_dot(2, w7, w21);
  /* #222: @23 = (-@12) */
  w23 = (- w12 );
  /* #223: @20 = horzcat(@27, @23) */
  rr=w20;
  *rr++ = w27;
  *rr++ = w23;
  /* #224: @20 = @20' */
  /* #225: @23 = dot(@20, @9) */
  w23 = casadi_dot(2, w20, w9);
  /* #226: @14 = (@14+@23) */
  w14 += w23;
  /* #227: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #228: @0 = (@0*@14) */
  w0 *= w14;
  /* #229: @7 = (@7*@0) */
  for (i=0, rr=w7; i<2; ++i) (*rr++) *= w0;
  /* #230: @20 = (@6*@20) */
  for (i=0, rr=w20, cs=w20; i<2; ++i) (*rr++)  = (w6*(*cs++));
  /* #231: @7 = (@7+@20) */
  for (i=0, rr=w7, cs=w20; i<2; ++i) (*rr++) += (*cs++);
  /* #232: @19 = (@19-@7) */
  for (i=0, rr=w19, cs=w7; i<2; ++i) (*rr++) -= (*cs++);
  /* #233: {@14, @23} = vertsplit(@19) */
  w14 = w19[0];
  w23 = w19[1];
  /* #234: (@1[1] += @23) */
  for (rr=w1+1, ss=(&w23); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #235: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #236: @17 = (@17*@27) */
  w17 *= w27;
  /* #237: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w7; i<2; ++i) (*rr++) += (*cs++);
  /* #238: @10 = @10' */
  /* #239: {@27, @14} = horzsplit(@10) */
  w27 = w10[0];
  w14 = w10[1];
  /* #240: @4 = (@4*@14) */
  w4 *= w14;
  /* #241: @17 = (@17+@4) */
  w17 += w4;
  /* #242: @16 = (@16*@12) */
  w16 *= w12;
  /* #243: @5 = (@5*@27) */
  w5 *= w27;
  /* #244: @16 = (@16+@5) */
  w16 += w5;
  /* #245: @17 = (@17+@16) */
  w17 += w16;
  /* #246: @35 = 00 */
  /* #247: {@16, NULL} = fwd1_jac_jac_traj(@2, @3, @3, @3, @35, @15, @3, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=(&w15);
  arg1[6]=0;
  arg1[7]=0;
  res1[0]=(&w16);
  res1[1]=0;
  if (casadi_f15(arg1, res1, iw, w, 0)) return 1;
  /* #248: @25 = (@25*@16) */
  w25 *= w16;
  /* #249: @10 = (@9*@8) */
  for (i=0, rr=w10, cr=w9; i<2; ++i) (*rr++)  = ((*cr++)*w8);
  /* #250: @7 = (@11*@21) */
  for (i=0, rr=w7, cs=w21; i<2; ++i) (*rr++)  = (w11*(*cs++));
  /* #251: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w7; i<2; ++i) (*rr++) += (*cs++);
  /* #252: @10 = @10' */
  /* #253: {@11, @8} = horzsplit(@10) */
  w11 = w10[0];
  w8 = w10[1];
  /* #254: @9 = (@9*@0) */
  for (i=0, rr=w9; i<2; ++i) (*rr++) *= w0;
  /* #255: @21 = (@6*@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) (*rr++)  = (w6*(*cs++));
  /* #256: @9 = (@9+@21) */
  for (i=0, rr=w9, cs=w21; i<2; ++i) (*rr++) += (*cs++);
  /* #257: @9 = @9' */
  /* #258: {@6, @0} = horzsplit(@9) */
  w6 = w9[0];
  w0 = w9[1];
  /* #259: @11 = (@11-@0) */
  w11 -= w0;
  /* #260: @24 = (@24*@11) */
  w24 *= w11;
  /* #261: @25 = (@25+@24) */
  w25 += w24;
  /* #262: @17 = (@17+@25) */
  w17 += w25;
  /* #263: {@25, NULL} = fwd1_jac_jac_traj(@2, @3, @3, @3, @35, @15, @3, @3) */
  arg1[0]=(&w2);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=(&w15);
  arg1[6]=0;
  arg1[7]=0;
  res1[0]=(&w25);
  res1[1]=0;
  if (casadi_f16(arg1, res1, iw, w, 0)) return 1;
  /* #264: @26 = (@26*@25) */
  w26 *= w25;
  /* #265: @8 = (@8+@6) */
  w8 += w6;
  /* #266: @28 = (@28*@8) */
  w28 *= w8;
  /* #267: @26 = (@26+@28) */
  w26 += w28;
  /* #268: @17 = (@17+@26) */
  w17 += w26;
  /* #269: (@1[12] += @17) */
  for (rr=w1+12, ss=(&w17); rr!=w1+13; rr+=1) *rr += *ss++;
  /* #270: @34 = @1[0, 1, 12] */
  for (cii=casadi_s12, rr=w34, ss=w1; cii!=casadi_s12+3; ++cii) *rr++ = ss[*cii];
  /* #271: (@29[7:10] = @34) */
  for (rr=w29+7, ss=w34; rr!=w29+10; rr+=1) *rr = *ss++;
  /* #272: (@29[3:12:3] = @34) */
  for (rr=w29+3, ss=w34; rr!=w29+12; rr+=3) *rr = *ss++;
  /* #273: @36 = @29' */
  casadi_trans(w29,casadi_s13, w36, casadi_s13, iw);
  /* #274: output[2][0] = @36 */
  casadi_copy(w36, 10, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s15;
    case 2: return casadi_s16;
    case 3: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    case 2: return casadi_s13;
    case 3: return casadi_s19;
    case 4: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 34;
  if (sz_w) *sz_w = 224;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_MJPC_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 34*sizeof(casadi_int);
  if (sz_w) *sz_w = 224*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
